Teamtreehouse/Projects/Ruby_Biller/config/routes.rb
Biller::Application.routes.draw do

  resources :accounts

  resources :employees do
    resources :time_entries
  end

end

Teamtreehouse/Projects/Ruby_Biller/app/models/account.rb
class Account < ActiveRecord::Base
	has_many :account_entries

	validates :name, presence: true,
									length: {in: 1..70},
									uniqueness: true
end

Teamtreehouse/Projects/Ruby_Biller/app/models/account_entry.rb
class AccountEntry < ActiveRecord::Base
  belongs_to :account

  validates :account_id, presence: true
  validates_associated :account
end

Teamtreehouse/Projects/Ruby_Biller/app/models/customer.rb
class Customer < Account
  has_many :time_entries
end

Teamtreehouse/Projects/Ruby_Biller/app/models/employee.rb
class Employee < Account
  has_many :time_entries
  has_and_belongs_to_many :projects, :join_table => "employees_projects"

  def total_hours
  	time_entries.sum(:time)
  end

  def log_time(amount, customer)
  	TimeEntry.create(time: amount, employee: self, account: customer)
  end
end

Teamtreehouse/Projects/Ruby_Biller/app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :customer
	has_and_belongs_to_many :employees, :join_table => "employees_projects"

	validates :name, presence: true, length: {in: 1..70}
end

Teamtreehouse/Projects/Ruby_Biller/app/models/time_entry.rb
class TimeEntry < AccountEntry
  belongs_to :employee
  validates :time, :numericality: {greater_than: 0, less_than: 24}
  def cost
    time * 34
  end
end

Teamtreehouse/Projects/Ruby_Biller/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	def index
		@accounts = Customer.all
	end

	def show
		@account = Account.find(params[:id])
	end
end

Teamtreehouse/Projects/Ruby_Biller/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Teamtreehouse/Projects/Ruby_Biller/app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def create
    e = Employee.create(params.require(:employee).permit(:name))
    redirect_to employee_path(e)
  end
end

Teamtreehouse/Projects/Ruby_Biller/app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  def create
    e = Employee.find(params[:employee_id])
    e.time_entries.create(params.require(:time_entry).permit(:time, :account_id))
    redirect_to employee_path(e)
  end
end

Teamtreehouse/Projects/Ruby_Biller/app/helpers/accounts_helper.rb
module AccountsHelper
end

Teamtreehouse/Projects/Ruby_Biller/app/helpers/application_helper.rb
module ApplicationHelper
end

Teamtreehouse/Projects/Ruby_Biller/app/helpers/employees_helper.rb
module EmployeesHelper
end

Teamtreehouse/Projects/Ruby_Biller/app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

Teamtreehouse/Projects/Ruby_Biller/app/views/accounts/index.html.erb
<table>
	<% @accounts.each do |account| %>
	<tr>
		<td><%= link_to account.name, account_path(account) %></td>
		<td><%= account.type.to_s %></td>
	</tr>
	<% end %>
</table>

Teamtreehouse/Projects/Ruby_Biller/app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>

Total Hours: <%= @account.account_entries.sum(:time) %>
Total Cost: $<%= (@account.account_entries.map &:cost).sum %>

<h4>Account Entries</h4>

<table>
	<% @account.account_entries.each do |entry| %>
	<tr>
		<td><%= entry.created_at %></td>
		<td><%= entry.employee.name %></td>
		<td><%= entry.time %> hours</td>
	</tr>
	<% end %>
</table>

Teamtreehouse/Projects/Ruby_Biller/app/views/employees/index.html.erb
<% @employees.each do |employee| %>
  <%= link_to employee.name, employee_path(employee) %>
<% end %>

<%= form_for Employee.new do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

Teamtreehouse/Projects/Ruby_Biller/app/views/employees/show.html.erb
<h1><%= @employee.name %></h1>

<h3>Submit time form</h3>
<%= form_for [@employee, TimeEntry.new] do |f| %>
  <%= f.label :customer %>
  <%= f.collection_select(:account_id, Customer.all, :id, :name) %>
  <%= f.label :time %>
  <%= f.text_field :time, :value => 1.0 %>
  <%= f.submit %>
<% end %>

<h3>Time Entries</h3>

<% @employee.time_entries.each do |entry| %>
  <div class="entry">
    <%= entry.time %>
    <%= entry.account.name %>
    <%= entry.created_at %>
  </div>
<% end %>

Teamtreehouse/Projects/Ruby_Biller/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biller</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>